-- ============================================================================
-- Phase 5: ML Pipeline — Bearing Failure Prediction
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PM_WH;
USE DATABASE PREDICTIVE_MAINTENANCE;
USE SCHEMA ML;

-- Feature engineering: daily aggregates per asset with 7-day trends and labels
CREATE OR REPLACE TABLE BEARING_FAILURE_FEATURES AS
WITH daily_sensor_stats AS (
    SELECT
        se.ASSET_ID, se.ASSET_NAME, se.ASSET_TYPE, se.MACHINE_CLASS, se.PLANT_ID,
        se.READING_TS::DATE AS READING_DATE,
        AVG(se.MAX_VEL_RMS) AS AVG_MAX_VEL, MAX(se.MAX_VEL_RMS) AS PEAK_VEL,
        STDDEV(se.MAX_VEL_RMS) AS VEL_STDDEV,
        AVG(se.RSS_ACCEL) AS AVG_RSS_ACCEL, MAX(se.RSS_ACCEL) AS PEAK_RSS_ACCEL,
        STDDEV(se.RSS_ACCEL) AS ACCEL_STDDEV,
        AVG(se.TEMPERATURE_C) AS AVG_TEMP, MAX(se.TEMPERATURE_C) AS MAX_TEMP,
        AVG(CASE WHEN se.ISO_VEL_ZONE = 'A_GOOD' THEN 1.0 ELSE 0.0 END) AS FRAC_ZONE_A,
        AVG(CASE WHEN se.ISO_VEL_ZONE = 'B_SATISFACTORY' THEN 1.0 ELSE 0.0 END) AS FRAC_ZONE_B,
        AVG(se.VEL_ZSCORE) AS AVG_ZSCORE, MAX(ABS(se.VEL_ZSCORE)) AS MAX_ABS_ZSCORE,
        AVG(CASE WHEN se.TEMP_STATUS != 'NORMAL' THEN 1.0 ELSE 0.0 END) AS FRAC_TEMP_ALARM
    FROM CURATED.DT_SENSOR_ENRICHED se
    GROUP BY se.ASSET_ID, se.ASSET_NAME, se.ASSET_TYPE, se.MACHINE_CLASS, se.PLANT_ID, se.READING_TS::DATE
),
with_trends AS (
    SELECT d.*,
        AVG(d.AVG_MAX_VEL) OVER (PARTITION BY d.ASSET_ID ORDER BY d.READING_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS VEL_7D_AVG,
        AVG(d.AVG_RSS_ACCEL) OVER (PARTITION BY d.ASSET_ID ORDER BY d.READING_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ACCEL_7D_AVG,
        AVG(d.AVG_TEMP) OVER (PARTITION BY d.ASSET_ID ORDER BY d.READING_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS TEMP_7D_AVG,
        d.AVG_MAX_VEL - AVG(d.AVG_MAX_VEL) OVER (PARTITION BY d.ASSET_ID ORDER BY d.READING_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS VEL_DELTA_7D,
        d.AVG_RSS_ACCEL - AVG(d.AVG_RSS_ACCEL) OVER (PARTITION BY d.ASSET_ID ORDER BY d.READING_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ACCEL_DELTA_7D,
        d.AVG_TEMP - AVG(d.AVG_TEMP) OVER (PARTITION BY d.ASSET_ID ORDER BY d.READING_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS TEMP_DELTA_7D,
        COALESCE(DATEDIFF('day', MAX(fi.FAILURE_TIMESTAMP::DATE) OVER (PARTITION BY d.ASSET_ID ORDER BY d.READING_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), d.READING_DATE), 999) AS DAYS_SINCE_LAST_FAILURE,
        COUNT(DISTINCT fi.INCIDENT_ID) OVER (PARTITION BY d.ASSET_ID ORDER BY d.READING_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_FAILURES
    FROM daily_sensor_stats d
    LEFT JOIN RAW.FAILURE_INCIDENTS fi ON d.ASSET_ID = fi.ASSET_ID AND fi.FAILURE_TIMESTAMP::DATE <= d.READING_DATE
),
labeled AS (
    SELECT wt.*,
        CASE WHEN EXISTS (
            SELECT 1 FROM RAW.FAILURE_INCIDENTS fi2
            WHERE fi2.ASSET_ID = wt.ASSET_ID
            AND fi2.FAILURE_TIMESTAMP::DATE BETWEEN wt.READING_DATE AND DATEADD('day', 7, wt.READING_DATE)
        ) THEN 1 ELSE 0 END AS FAILURE_WITHIN_7D
    FROM with_trends wt
)
SELECT * FROM labeled;

-- Cleaned feature view (excludes DATE column and null stddev rows)
CREATE OR REPLACE VIEW ML.BEARING_FAILURE_FEATURES_V AS
SELECT ASSET_TYPE, MACHINE_CLASS, AVG_MAX_VEL, PEAK_VEL, VEL_STDDEV,
    AVG_RSS_ACCEL, PEAK_RSS_ACCEL, ACCEL_STDDEV, AVG_TEMP, MAX_TEMP,
    FRAC_ZONE_A, FRAC_ZONE_B, AVG_ZSCORE, MAX_ABS_ZSCORE, FRAC_TEMP_ALARM,
    VEL_7D_AVG, ACCEL_7D_AVG, TEMP_7D_AVG, VEL_DELTA_7D, ACCEL_DELTA_7D, TEMP_DELTA_7D,
    DAYS_SINCE_LAST_FAILURE, CUMULATIVE_FAILURES, FAILURE_WITHIN_7D
FROM ML.BEARING_FAILURE_FEATURES WHERE VEL_STDDEV IS NOT NULL;

-- Train classification model
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION BEARING_FAILURE_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ML.BEARING_FAILURE_FEATURES_V'),
    TARGET_COLNAME => 'FAILURE_WITHIN_7D',
    CONFIG_OBJECT => {'ON_ERROR': 'SKIP', 'evaluate': TRUE}
);

-- Generate predictions for all current assets
CREATE OR REPLACE TABLE ML.BEARING_PREDICTIONS AS
WITH latest_features AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY ASSET_ID ORDER BY READING_DATE DESC) AS rn
    FROM ML.BEARING_FAILURE_FEATURES WHERE VEL_STDDEV IS NOT NULL
)
SELECT ASSET_ID, ASSET_NAME, ASSET_TYPE, PLANT_ID, READING_DATE AS PREDICTION_DATE,
    BEARING_FAILURE_MODEL!PREDICT(INPUT_DATA => {
        'ASSET_TYPE': ASSET_TYPE, 'MACHINE_CLASS': MACHINE_CLASS,
        'AVG_MAX_VEL': AVG_MAX_VEL, 'PEAK_VEL': PEAK_VEL, 'VEL_STDDEV': VEL_STDDEV,
        'AVG_RSS_ACCEL': AVG_RSS_ACCEL, 'PEAK_RSS_ACCEL': PEAK_RSS_ACCEL, 'ACCEL_STDDEV': ACCEL_STDDEV,
        'AVG_TEMP': AVG_TEMP, 'MAX_TEMP': MAX_TEMP,
        'FRAC_ZONE_A': FRAC_ZONE_A, 'FRAC_ZONE_B': FRAC_ZONE_B,
        'AVG_ZSCORE': AVG_ZSCORE, 'MAX_ABS_ZSCORE': MAX_ABS_ZSCORE, 'FRAC_TEMP_ALARM': FRAC_TEMP_ALARM,
        'VEL_7D_AVG': VEL_7D_AVG, 'ACCEL_7D_AVG': ACCEL_7D_AVG, 'TEMP_7D_AVG': TEMP_7D_AVG,
        'VEL_DELTA_7D': VEL_DELTA_7D, 'ACCEL_DELTA_7D': ACCEL_DELTA_7D, 'TEMP_DELTA_7D': TEMP_DELTA_7D,
        'DAYS_SINCE_LAST_FAILURE': DAYS_SINCE_LAST_FAILURE, 'CUMULATIVE_FAILURES': CUMULATIVE_FAILURES
    }) AS PREDICTION_RESULT
FROM latest_features WHERE rn = 1;

-- Flattened predictions view with risk tiers
CREATE OR REPLACE VIEW ML.BEARING_PREDICTIONS_V AS
SELECT bp.ASSET_ID, bp.ASSET_NAME, bp.ASSET_TYPE, bp.PLANT_ID, p.PLANT_NAME,
    bp.PREDICTION_DATE,
    bp.PREDICTION_RESULT:class::STRING AS PREDICTED_FAILURE,
    ROUND(bp.PREDICTION_RESULT:probability:"1"::FLOAT, 6) AS FAILURE_PROBABILITY,
    CASE
        WHEN bp.PREDICTION_RESULT:probability:"1"::FLOAT >= 0.75 THEN 'CRITICAL'
        WHEN bp.PREDICTION_RESULT:probability:"1"::FLOAT >= 0.50 THEN 'HIGH'
        WHEN bp.PREDICTION_RESULT:probability:"1"::FLOAT >= 0.10 THEN 'MEDIUM'
        WHEN bp.PREDICTION_RESULT:probability:"1"::FLOAT >= 0.01 THEN 'LOW'
        ELSE 'MINIMAL'
    END AS RISK_TIER,
    bh.BEARING_HEALTH_SCORE, bh.ADR_RISK,
    bh.PEAK_VEL_RMS AS CURRENT_PEAK_VEL,
    bh.PEAK_RSS_ACCEL AS CURRENT_PEAK_ACCEL,
    bh.MAX_TEMPERATURE_C AS CURRENT_MAX_TEMP
FROM ML.BEARING_PREDICTIONS bp
JOIN RAW.PLANTS p ON bp.PLANT_ID = p.PLANT_ID
LEFT JOIN CURATED.DT_BEARING_HEALTH bh ON bp.ASSET_ID = bh.ASSET_ID;
